/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pointofsale;

import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALPHA
 */
public class DetailTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form DetailTransaksi
     * 
     */
    
    public static DefaultTableModel tb = new DefaultTableModel();
    
    public DetailTransaksi(String id_transaksi) {
        initComponents();
        this.setResizable(false);
        
        this.setTitle("Detail Transaksi");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/pointofsale/src/trolley.png")));
       
        try{
        
            String sql_transaksi = "SELECT transaksi.kode_transaksi, transaksi.diskon, transaksi.diskon, transaksi.grand_total, transaksi.tunai, users.nama_lengkap, transaksi.created_at FROM transaksi JOIN users ON transaksi.id_user = users.id_user WHERE kode_transaksi = ?";
            PreparedStatement pst = Dashboard.conn.prepareStatement(sql_transaksi);
            pst.setString(1, id_transaksi);
            ResultSet res = pst.executeQuery();
            
            if(res.next()){
                label_id_transaksi.setText("ID "+res.getString("transaksi.kode_transaksi"));
                label_kasir.setText("Kasir : "+ res.getString("users.nama_lengkap"));
                tanggal_dan_waktu.setText("Tanggal dan Waktu : "+ res.getString("transaksi.created_at"));
                label_diskon.setText("Diskon : "+ res.getString("transaksi.diskon"));
                label_total.setText("Total : "+ res.getString("transaksi.grand_total"));
                label_tunai.setText("Tunai : "+ res.getString("transaksi.tunai"));
                
                tb.setColumnCount(0);
                tb.addColumn("Kode Barang");
                tb.addColumn("Qyt");
                tb.addColumn("Sub Total");

                table_detail_transaksi.setModel(tb);
                table_detail_transaksi.setEnabled(true);
                tb.setRowCount(0);
                
                String sql_detail_transaksi = "SELECT kode_barang, qyt, sub_total FROM transaksi_detail WHERE kode_transaksi = ?";
                PreparedStatement pst_sql_d = Dashboard.conn.prepareStatement(sql_detail_transaksi);
                pst_sql_d.setString(1, id_transaksi);
                ResultSet res_2 = pst_sql_d.executeQuery();
                
                while(res_2.next()){
                    tb.addRow(new Object[]{
                        res_2.getString(1),
                        res_2.getString(2),
                        res_2.getString(3)
                    });
                }
                
            }
            
        }catch(SQLException err){
            System.out.println(err);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_id_transaksi = new javax.swing.JLabel();
        label_kasir = new javax.swing.JLabel();
        tanggal_dan_waktu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_detail_transaksi = new javax.swing.JTable();
        label_diskon = new javax.swing.JLabel();
        label_tunai = new javax.swing.JLabel();
        label_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_id_transaksi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        label_id_transaksi.setText("ID TR02938123321");

        label_kasir.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        label_kasir.setText("Kasir : Aristo Caesar Pratama");

        tanggal_dan_waktu.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tanggal_dan_waktu.setText("Tanggal dan Waktu : 423432432");

        table_detail_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_detail_transaksi.setRowHeight(35);
        jScrollPane1.setViewportView(table_detail_transaksi);

        label_diskon.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        label_diskon.setText("Diskon");

        label_tunai.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        label_tunai.setText("Tunai");

        label_total.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        label_total.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_id_transaksi)
                            .addComponent(label_kasir)
                            .addComponent(tanggal_dan_waktu))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_diskon)
                        .addGap(247, 247, 247)
                        .addComponent(label_total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_tunai)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_id_transaksi)
                .addGap(18, 18, 18)
                .addComponent(label_kasir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggal_dan_waktu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_diskon)
                    .addComponent(label_total)
                    .addComponent(label_tunai))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new DetailTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_diskon;
    private javax.swing.JLabel label_id_transaksi;
    private javax.swing.JLabel label_kasir;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel label_tunai;
    private javax.swing.JTable table_detail_transaksi;
    private javax.swing.JLabel tanggal_dan_waktu;
    // End of variables declaration//GEN-END:variables
}
