/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pointofsale;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author PLAYER
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    public static java.sql.Connection conn = (Connection)Database.configDB();
    public static Utilities utilities = new Utilities();
    
    public Print(String id_transaksi, String nama_user, String data_jam, String[][] data_order, int banyak_order, String sub_total, String data_diskon, String data_total, String tunai, String kembalian) {
        initComponents();
        
        Dashboard.resetDataOrder(false);
        
        this.setTitle("Struk Pembayaran");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/pointofsale/src/trolley.png")));
        
        
        try{
            String sql = "SELECT * FROM toko ORDER BY id_toko ASC LIMIT 1";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet res = pst.executeQuery();
            
            if(res.next()){
                invoice_area.setText(res.getString(2)+"\n");
                invoice_area.setText(invoice_area.getText() + res.getString(3) +"\n");
                invoice_area.setText(invoice_area.getText() + res.getString(4) +"\n");
                invoice_area.setText(invoice_area.getText() + "--------------------------------------------------------------------------------------------------------------------------------------\n");
                invoice_area.setText(invoice_area.getText() + "ID : "+ id_transaksi + "\n");
                invoice_area.setText(invoice_area.getText() + "Kasir : "+ nama_user + "\n");
                invoice_area.setText(invoice_area.getText() + "Tanggal Dan Waktu : "+ utilities.getCurrentTimeStamp() + "\n");
                invoice_area.setText(invoice_area.getText() + "--------------------------------------------------------------------------------------------------------------------------------------\n");
                invoice_area.setText(invoice_area.getText() + "Barang                                                                             Harga          QYT         Diskon        Total\n");
                invoice_area.setText(invoice_area.getText() + "--------------------------------------------------------------------------------------------------------------------------------------\n");
                for(int i = 0; i < data_order.length; i++){
                    String nama_barang = data_order[i][1];
                    nama_barang = nama_barang.substring(0, Math.min(nama_barang.length(), 46));
                    invoice_area.setText(invoice_area.getText() +nama_barang+"     "+data_order[i][2]+"          "+data_order[i][4]+"             "+data_order[i][5]+"             "+data_order[i][6]+"\n");
                }
                invoice_area.setText(invoice_area.getText() + "--------------------------------------------------------------------------------------------------------------------------------------\n");
                invoice_area.setText(invoice_area.getText() + "Banyak Pembelian : " + banyak_order + "\n");
                invoice_area.setText(invoice_area.getText() + "Sub Total : " + sub_total + "\n");
                invoice_area.setText(invoice_area.getText() + "Diskon : "+ data_diskon + "\n");
                invoice_area.setText(invoice_area.getText() + "TOTAL : "+ data_total + "\n");
                invoice_area.setText(invoice_area.getText() + "--------------------------------------------------------------------------------------------------------------------------------------\n");
                invoice_area.setText(invoice_area.getText() + "Total Bayar : "+ tunai + "\n");
                invoice_area.setText(invoice_area.getText() + "Kembalian : "+ kembalian + "\n");
            }

            printInvoice();
        }catch(SQLException err){
            System.out.println(err);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invoice_area = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btn_print_again = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        invoice_area.setColumns(20);
        invoice_area.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        invoice_area.setRows(5);
        jScrollPane1.setViewportView(invoice_area);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("TUTUP");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btn_print_again.setBackground(new java.awt.Color(0, 102, 255));
        btn_print_again.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_print_again.setForeground(new java.awt.Color(255, 255, 255));
        btn_print_again.setText("PRINT");
        btn_print_again.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_print_againMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btn_print_again, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print_again, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_print_againMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_print_againMouseClicked
        // TODO add your handling code here:
        printInvoice();
    }//GEN-LAST:event_btn_print_againMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    public void printInvoice(){
        try{
            invoice_area.print();
        }catch(Exception err){
            System.out.println(err.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_print_again;
    private javax.swing.JTextArea invoice_area;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
