/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pointofsale;

/**
 *
 * @author Alkaafi Komputer
 */
public class TambahUser extends javax.swing.JFrame {

    /**
     * Creates new form tambahuser
     */
    public TambahUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_namadepan_tambahuser = new javax.swing.JTextField();
        field_namabelakang_tambahuser = new javax.swing.JTextField();
        field_username_tambahuser = new javax.swing.JTextField();
        field_notelpon_tambahuser = new javax.swing.JTextField();
        field_password_tambahuser = new javax.swing.JTextField();
        field_konfirmasipassword_tambahuser = new javax.swing.JTextField();
        button_simpan_tambahuser = new javax.swing.JButton();
        label_namadepan_tambahuser = new javax.swing.JLabel();
        label_namabelakang_tambahuser = new javax.swing.JLabel();
        label_username_tambahuser = new javax.swing.JLabel();
        label_notelp_tambahuser = new javax.swing.JLabel();
        label_password_tambahuser = new javax.swing.JLabel();
        label_konfirmasipassword_tambahuser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        field_namadepan_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        field_namadepan_tambahuser.setBorder(null);

        field_namabelakang_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        field_namabelakang_tambahuser.setBorder(null);

        field_username_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        field_username_tambahuser.setBorder(null);

        field_notelpon_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        field_notelpon_tambahuser.setBorder(null);

        field_password_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        field_password_tambahuser.setBorder(null);

        field_konfirmasipassword_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        field_konfirmasipassword_tambahuser.setBorder(null);

        button_simpan_tambahuser.setBackground(new java.awt.Color(73, 148, 255));
        button_simpan_tambahuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_simpan_tambahuser.setForeground(new java.awt.Color(255, 255, 255));
        button_simpan_tambahuser.setText("SIMPAN");
        button_simpan_tambahuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label_namadepan_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        label_namadepan_tambahuser.setText("Nama Depan");

        label_namabelakang_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        label_namabelakang_tambahuser.setText("Nama Belakang");

        label_username_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        label_username_tambahuser.setText("Username");

        label_notelp_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        label_notelp_tambahuser.setText("No. Telp");

        label_password_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        label_password_tambahuser.setText("Password");

        label_konfirmasipassword_tambahuser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        label_konfirmasipassword_tambahuser.setText("Konfirmasi Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_password_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_konfirmasipassword_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(button_simpan_tambahuser))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(field_password_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(field_konfirmasipassword_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_namadepan_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_namadepan_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_namabelakang_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field_namabelakang_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_username_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_username_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_notelp_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field_notelpon_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_namadepan_tambahuser)
                    .addComponent(label_namabelakang_tambahuser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_namadepan_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_namabelakang_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_username_tambahuser)
                    .addComponent(label_notelp_tambahuser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_username_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_notelpon_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_password_tambahuser)
                    .addComponent(label_konfirmasipassword_tambahuser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_password_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_konfirmasipassword_tambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(button_simpan_tambahuser)
                .addGap(31, 31, 31))
        );

        setSize(new java.awt.Dimension(729, 363));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_simpan_tambahuser;
    private javax.swing.JTextField field_konfirmasipassword_tambahuser;
    private javax.swing.JTextField field_namabelakang_tambahuser;
    private javax.swing.JTextField field_namadepan_tambahuser;
    private javax.swing.JTextField field_notelpon_tambahuser;
    private javax.swing.JTextField field_password_tambahuser;
    private javax.swing.JTextField field_username_tambahuser;
    private javax.swing.JLabel label_konfirmasipassword_tambahuser;
    private javax.swing.JLabel label_namabelakang_tambahuser;
    private javax.swing.JLabel label_namadepan_tambahuser;
    private javax.swing.JLabel label_notelp_tambahuser;
    private javax.swing.JLabel label_password_tambahuser;
    private javax.swing.JLabel label_username_tambahuser;
    // End of variables declaration//GEN-END:variables
}
